[Interface]
PrivateKey = EPof+z/GTzeXXBRXw9h526XcWTasBhRb/jmwKqCTZmY=
Address = 10.160.211.2/24,fd11:5ee:bad:c0b4::002/64
DNS = 192.168.1.166

[Peer]
PublicKey = SJSBV+3ijSc2lLj87Hzi8yhLvcKEgkwBD43i4etd4y0=
PresharedKey = yZdBB/8nP1Nse7GehOt1M1eElbuFzZUyZb9/fVD2Qfk=
Endpoint = ddns_v6.hootguard.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
