backup_items:
  /etc/lighttpd: lighttpd
  /etc/pihole: pihole
  /etc/pihole/setupVars.conf: setupVars.conf
  /etc/sudoers.d/hootguard: sudoers.d
  /etc/unbound/unbound.conf.d: unbound_conf.d
  /etc/systemd/system: systemd_system
  /etc/hosts: hosts
  /etc/hostname: hostname
  /etc/resolvconf.conf: resolvconf.conf
  /etc/dhcpcd.conf: dhcpcd.conf
  /etc/dhcpcd.conf.bkp: dhcpcd.conf.bkp
  /etc/dhcpcd.conf.original: dhcpcd.conf.original
  /var/www/html/index.html: index.html
  /var/www/html/hootguard: hootguard_html
  /opt/hootguard: opt_hootguard
  /boot/config.txt: config.txt

exclude_from_update:
  - /etc/dhcpcd.conf
  - /etc/unbound/unbound.conf.d/root-auto-trust-anchor-file.conf

permissions:
  - [chmod 0644, /boot/config.txt]
  - [chmod 0644, /etc/lighttpd/lighttpd.conf]
  - [chmod 0644, /etc/pihole/setupVars.conf]
  - [chmod 0440, /etc/sudoers.d/hootguard]
  - [chmod 0644, /etc/systemd/system/hg-deactivate-i2c.service]
  - [chmod 0644 /etc/systemd/system/hg-info-display.service]
  - [chmod 0644 /etc/systemd/system/hg-main.service]
  - [chmod 0644 /etc/systemd/system/hg-ntp-update.service]
  - [chmod 0644 /etc/systemd/system/hg-reset.service]
  - [chmod 0644 /etc/systemd/system/hg-snooze.service]
  - [chmod 0644 /etc/unbound/unbound.conf.d/pi-hole.conf]
  - [chmod 0644 /etc/dhcpcd.conf.bkp]
  - [chmod 0644 /etc/dhcpcd.conf.original]
  - [chmod 0644 /etc/hostname]
  - [chmod 0644 /etc/hosts]
  - [chmod 0644 /etc/resolvconf.conf]
  - [chmod 0700 /usr/local/bin/hootguard]

ownership:
  - [chown root:root, /boot/config.txt]
  - [chown root:root, /etc/lighttpd/lighttpd.conf]
  - [chown root:root, /etc/pihole/setupVars.conf]
  - [chown root:root /etc/sudoers.d/hootguard]
  - [chown root:root /etc/systemd/system/hg-deactivate-i2c.service]
  - [chown root:root /etc/systemd/system/hg-info-display.service]
  - [chown root:root /etc/systemd/system/hg-main.service]
  - [chown root:root /etc/systemd/system/hg-ntp-update.service]
  - [chown root:root /etc/systemd/system/hg-reset.service]
  - [chown root:root /etc/systemd/system/hg-snooze.service]
  - [chown root:root /etc/unbound/unbound.conf.d/pi-hole.conf]
  - [chown root:root /etc/dhcpcd.conf.bkp]
  - [chown root:root /etc/dhcpcd.conf.original]
  - [chown root:root /etc/hostname]
  - [chown root:root /etc/hosts]
  - [chown root:root /etc/resolvconf.conf]
  - [chown root:root /usr/local/bin/hootguard]

services:
  - hg-main.service
  - pihole-FTL.service
  - unbound.service
